default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASS"] %>

development:
  <<: *default
  database: sun-ecommerces

test:
  <<: *default
  database: sun-ecommerces

production:
  <<: *default
  database: sun-ecommerces
